
-- CMS setup for Inner Service Area Pages

INSERT INTO admin_sidebar (id, label, icon, order_index, parent_id)
VALUES ('page_service_area_inner', 'Area Detail Pages', '📍', 5, 'services_group')
ON CONFLICT (id) DO NOTHING;

INSERT INTO site_content (key, section, type, label, value)
VALUES
('territory.richmond-hill.heroImage', 'page_service_area_inner', 'image', 'Richmond Hill Hero Image', '/optimized/webp_gen_luxury_glass_mansion.webp'),
('territory.richmond-hill.heroTargetLock', 'page_service_area_inner', 'text', 'Richmond Hill Hero Target Lock Focus', 'Target Lock: Richmond Hill'),
('territory.richmond-hill.heroTitleTop', 'page_service_area_inner', 'text', 'Richmond Hill Hero Title Top', 'Commanding Architecture in'),
('territory.richmond-hill.heroTitleBot', 'page_service_area_inner', 'text', 'Richmond Hill Hero Title Bottom', 'Richmond Hill'),
('territory.richmond-hill.heroDesc', 'page_service_area_inner', 'text', 'Richmond Hill Hero Subheadline', 'Dominating the northern suburban luxury market.'),
('territory.richmond-hill.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Richmond Hill Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.richmond-hill.bylawsTitle1', 'page_service_area_inner', 'text', 'Richmond Hill Bylaws Title Part 1', 'CONQUERING'),
('territory.richmond-hill.bylawsTitle2', 'page_service_area_inner', 'text', 'Richmond Hill Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.richmond-hill.bylawsDesc', 'page_service_area_inner', 'text', 'Richmond Hill Bylaws Description', 'You cannot engineer a multi-million dollar estate in Richmond Hill without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Richmond Hill''s hardest zoning restrictions.'),
('territory.richmond-hill.bylaw1Title', 'page_service_area_inner', 'text', 'Richmond Hill Bylaw Item 1 Title', 'TRCA Regulations'),
('territory.richmond-hill.bylaw1Desc', 'page_service_area_inner', 'text', 'Richmond Hill Bylaw Item 1 Description', 'Navigating Toronto and Region Conservation Authority boundaries to maximize rear yard usage without triggering environmental red flags.'),
('territory.richmond-hill.bylaw2Title', 'page_service_area_inner', 'text', 'Richmond Hill Bylaw Item 2 Title', 'Zoning Variances'),
('territory.richmond-hill.bylaw2Desc', 'page_service_area_inner', 'text', 'Richmond Hill Bylaw Item 2 Description', 'Securing Committee of Adjustment approvals for aggressive multi-story height expansions across premium mature neighborhoods.'),
('territory.richmond-hill.projectTitle', 'page_service_area_inner', 'text', 'Richmond Hill Featured Project Title', 'The Bayview Compound'),
('territory.richmond-hill.projectCategory', 'page_service_area_inner', 'text', 'Richmond Hill Featured Project Category', 'Custom Home Building'),
('territory.richmond-hill.projectImage', 'page_service_area_inner', 'image', 'Richmond Hill Featured Project Image', '/optimized/webp_gen_concrete_contemporary.webp'),
('territory.richmond-hill.projectScope', 'page_service_area_inner', 'text', 'Richmond Hill Featured Project Scope', 'Deep structural underpinning and massive lateral expansion.'),
('territory.richmond-hill.projectTimeline', 'page_service_area_inner', 'text', 'Richmond Hill Featured Project Timeline', '14 months to keys-in-hand'),
('territory.richmond-hill.portfolioTitle', 'page_service_area_inner', 'text', 'Richmond Hill Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.richmond-hill.portfolioDesc', 'page_service_area_inner', 'text', 'Richmond Hill Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Richmond Hill.'),
('territory.oakville.heroImage', 'page_service_area_inner', 'image', 'Oakville Hero Image', '/optimized/webp_gen_brutalist_villa.webp'),
('territory.oakville.heroTargetLock', 'page_service_area_inner', 'text', 'Oakville Hero Target Lock Focus', 'Target Lock: Oakville'),
('territory.oakville.heroTitleTop', 'page_service_area_inner', 'text', 'Oakville Hero Title Top', 'Elite Lakeshore Architecture'),
('territory.oakville.heroTitleBot', 'page_service_area_inner', 'text', 'Oakville Hero Title Bottom', 'in Oakville'),
('territory.oakville.heroDesc', 'page_service_area_inner', 'text', 'Oakville Hero Subheadline', 'Navigating Halton Conservation for waterfront supremacy.'),
('territory.oakville.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Oakville Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.oakville.bylawsTitle1', 'page_service_area_inner', 'text', 'Oakville Bylaws Title Part 1', 'CONQUERING'),
('territory.oakville.bylawsTitle2', 'page_service_area_inner', 'text', 'Oakville Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.oakville.bylawsDesc', 'page_service_area_inner', 'text', 'Oakville Bylaws Description', 'You cannot engineer a multi-million dollar estate in Oakville without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Oakville''s hardest zoning restrictions.'),
('territory.oakville.bylaw1Title', 'page_service_area_inner', 'text', 'Oakville Bylaw Item 1 Title', 'Lakeshore Setbacks'),
('territory.oakville.bylaw1Desc', 'page_service_area_inner', 'text', 'Oakville Bylaw Item 1 Description', 'Pushing construction as close to the Lake Ontario waterline as mathematically and legally possible using engineered retaining structures.'),
('territory.oakville.bylaw2Title', 'page_service_area_inner', 'text', 'Oakville Bylaw Item 2 Title', 'Halton Conservation'),
('territory.oakville.bylaw2Desc', 'page_service_area_inner', 'text', 'Oakville Bylaw Item 2 Description', 'Seamlessly filing and obtaining aggressive Halton Region conservation permits for uncompromised structural footprints.'),
('territory.oakville.projectTitle', 'page_service_area_inner', 'text', 'Oakville Featured Project Title', 'The Oakville Lakeshore Glass'),
('territory.oakville.projectCategory', 'page_service_area_inner', 'text', 'Oakville Featured Project Category', 'Structural Engineering'),
('territory.oakville.projectImage', 'page_service_area_inner', 'image', 'Oakville Featured Project Image', '/optimized/webp_gen_commercial_skyscraper.webp'),
('territory.oakville.projectScope', 'page_service_area_inner', 'text', 'Oakville Featured Project Scope', 'Triple-paned floor-to-ceiling automated envelope over a helical steel staircase.'),
('territory.oakville.projectTimeline', 'page_service_area_inner', 'text', 'Oakville Featured Project Timeline', '18 months execution'),
('territory.oakville.portfolioTitle', 'page_service_area_inner', 'text', 'Oakville Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.oakville.portfolioDesc', 'page_service_area_inner', 'text', 'Oakville Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Oakville.'),
('territory.vaughan.heroImage', 'page_service_area_inner', 'image', 'Vaughan Hero Image', '/optimized/webp_gen_corporate_lowrise.webp'),
('territory.vaughan.heroTargetLock', 'page_service_area_inner', 'text', 'Vaughan Hero Target Lock Focus', 'Target Lock: Vaughan'),
('territory.vaughan.heroTitleTop', 'page_service_area_inner', 'text', 'Vaughan Hero Title Top', 'Multi-Acre Mastery'),
('territory.vaughan.heroTitleBot', 'page_service_area_inner', 'text', 'Vaughan Hero Title Bottom', 'in Vaughan'),
('territory.vaughan.heroDesc', 'page_service_area_inner', 'text', 'Vaughan Hero Subheadline', 'Engineering massive square-footage estates without compromise.'),
('territory.vaughan.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Vaughan Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.vaughan.bylawsTitle1', 'page_service_area_inner', 'text', 'Vaughan Bylaws Title Part 1', 'CONQUERING'),
('territory.vaughan.bylawsTitle2', 'page_service_area_inner', 'text', 'Vaughan Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.vaughan.bylawsDesc', 'page_service_area_inner', 'text', 'Vaughan Bylaws Description', 'You cannot engineer a multi-million dollar estate in Vaughan without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Vaughan''s hardest zoning restrictions.'),
('territory.vaughan.bylaw1Title', 'page_service_area_inner', 'text', 'Vaughan Bylaw Item 1 Title', 'Massive Footprints'),
('territory.vaughan.bylaw1Desc', 'page_service_area_inner', 'text', 'Vaughan Bylaw Item 1 Description', 'Leveraging Vaughan''s zoning to execute expansive multi-acre floor plans, huge lateral garages, and sweeping circular drives.'),
('territory.vaughan.bylaw2Title', 'page_service_area_inner', 'text', 'Vaughan Bylaw Item 2 Title', 'Stormwater Management'),
('territory.vaughan.bylaw2Desc', 'page_service_area_inner', 'text', 'Vaughan Bylaw Item 2 Description', 'Implementing required rapid transit and stormwater infiltration galleries beneath luxury interlock courtyards to satisfy city mandates.'),
('territory.vaughan.projectTitle', 'page_service_area_inner', 'text', 'Vaughan Featured Project Title', 'The Woodbridge Estate'),
('territory.vaughan.projectCategory', 'page_service_area_inner', 'text', 'Vaughan Featured Project Category', 'New Ground Up Build'),
('territory.vaughan.projectImage', 'page_service_area_inner', 'image', 'Vaughan Featured Project Image', '/optimized/webp_gen_luxury_kitchen.webp'),
('territory.vaughan.projectScope', 'page_service_area_inner', 'text', 'Vaughan Featured Project Scope', 'Ground-up execution featuring a 10-car subterranean parking matrix.'),
('territory.vaughan.projectTimeline', 'page_service_area_inner', 'text', 'Vaughan Featured Project Timeline', '20 months construction'),
('territory.vaughan.portfolioTitle', 'page_service_area_inner', 'text', 'Vaughan Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.vaughan.portfolioDesc', 'page_service_area_inner', 'text', 'Vaughan Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Vaughan.'),
('territory.king-city.heroImage', 'page_service_area_inner', 'image', 'King City Hero Image', '/optimized/webp_gen_marble_foyer.webp'),
('territory.king-city.heroTargetLock', 'page_service_area_inner', 'text', 'King City Hero Target Lock Focus', 'Target Lock: King City'),
('territory.king-city.heroTitleTop', 'page_service_area_inner', 'text', 'King City Hero Title Top', 'The Apex of Suburban Luxury:'),
('territory.king-city.heroTitleBot', 'page_service_area_inner', 'text', 'King City Hero Title Bottom', 'King City'),
('territory.king-city.heroDesc', 'page_service_area_inner', 'text', 'King City Hero Subheadline', 'Palatial multi-acre estates built for multi-generational wealth.'),
('territory.king-city.bylawsSuperTitle', 'page_service_area_inner', 'text', 'King City Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.king-city.bylawsTitle1', 'page_service_area_inner', 'text', 'King City Bylaws Title Part 1', 'CONQUERING'),
('territory.king-city.bylawsTitle2', 'page_service_area_inner', 'text', 'King City Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.king-city.bylawsDesc', 'page_service_area_inner', 'text', 'King City Bylaws Description', 'You cannot engineer a multi-million dollar estate in King City without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving King City''s hardest zoning restrictions.'),
('territory.king-city.bylaw1Title', 'page_service_area_inner', 'text', 'King City Bylaw Item 1 Title', 'Oak Ridges Moraine'),
('territory.king-city.bylaw1Desc', 'page_service_area_inner', 'text', 'King City Bylaw Item 1 Description', 'Absolute compliance and aggressive navigation of the Oak Ridges Moraine conservation act to build massive footprint compounds.'),
('territory.king-city.bylaw2Title', 'page_service_area_inner', 'text', 'King City Bylaw Item 2 Title', 'Private Infrastructure'),
('territory.king-city.bylaw2Desc', 'page_service_area_inner', 'text', 'King City Bylaw Item 2 Description', 'Engineering isolated septic, deep well, and multi-zone hydro infrastructure completely independent from standard municipal grids.'),
('territory.king-city.projectTitle', 'page_service_area_inner', 'text', 'King City Featured Project Title', 'The King City Brutalist Villa'),
('territory.king-city.projectCategory', 'page_service_area_inner', 'text', 'King City Featured Project Category', 'Architectural Concrete'),
('territory.king-city.projectImage', 'page_service_area_inner', 'image', 'King City Featured Project Image', '/optimized/webp_gen_boardroom.webp'),
('territory.king-city.projectScope', 'page_service_area_inner', 'text', 'King City Featured Project Scope', 'Poured-in-place concrete architecture with 12ft interior commercial steel ceilings.'),
('territory.king-city.projectTimeline', 'page_service_area_inner', 'text', 'King City Featured Project Timeline', '16 months complete cycle'),
('territory.king-city.portfolioTitle', 'page_service_area_inner', 'text', 'King City Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.king-city.portfolioDesc', 'page_service_area_inner', 'text', 'King City Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across King City.'),
('territory.kleinburg.heroImage', 'page_service_area_inner', 'image', 'Kleinburg Hero Image', '/optimized/webp_gen_deck_pool.webp'),
('territory.kleinburg.heroTargetLock', 'page_service_area_inner', 'text', 'Kleinburg Hero Target Lock Focus', 'Target Lock: Kleinburg'),
('territory.kleinburg.heroTitleTop', 'page_service_area_inner', 'text', 'Kleinburg Hero Title Top', 'Historic Elegance'),
('territory.kleinburg.heroTitleBot', 'page_service_area_inner', 'text', 'Kleinburg Hero Title Bottom', 'in Kleinburg'),
('territory.kleinburg.heroDesc', 'page_service_area_inner', 'text', 'Kleinburg Hero Subheadline', 'Blending ultra-modern luxury against a century-old backdrop.'),
('territory.kleinburg.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Kleinburg Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.kleinburg.bylawsTitle1', 'page_service_area_inner', 'text', 'Kleinburg Bylaws Title Part 1', 'CONQUERING'),
('territory.kleinburg.bylawsTitle2', 'page_service_area_inner', 'text', 'Kleinburg Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.kleinburg.bylawsDesc', 'page_service_area_inner', 'text', 'Kleinburg Bylaws Description', 'You cannot engineer a multi-million dollar estate in Kleinburg without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Kleinburg''s hardest zoning restrictions.'),
('territory.kleinburg.bylaw1Title', 'page_service_area_inner', 'text', 'Kleinburg Bylaw Item 1 Title', 'Heritage Integration'),
('territory.kleinburg.bylaw1Desc', 'page_service_area_inner', 'text', 'Kleinburg Bylaw Item 1 Description', 'Appeasing local historical aesthetic boards while aggressively building massive, modern smart-homes behind traditional facades.'),
('territory.kleinburg.bylaw2Title', 'page_service_area_inner', 'text', 'Kleinburg Bylaw Item 2 Title', 'Ravine Protection'),
('territory.kleinburg.bylaw2Desc', 'page_service_area_inner', 'text', 'Kleinburg Bylaw Item 2 Description', 'Securing deep hillside piles and caissons to safely construct infinity pools and glass pavilions hanging over protected ravines.'),
('territory.kleinburg.projectTitle', 'page_service_area_inner', 'text', 'Kleinburg Featured Project Title', 'The Kleinburg Modern Estate'),
('territory.kleinburg.projectCategory', 'page_service_area_inner', 'text', 'Kleinburg Featured Project Category', 'Exterior Improvements'),
('territory.kleinburg.projectImage', 'page_service_area_inner', 'image', 'Kleinburg Featured Project Image', '/optimized/webp_gen_industrial_loft.webp'),
('territory.kleinburg.projectScope', 'page_service_area_inner', 'text', 'Kleinburg Featured Project Scope', 'Massive rear landscaping extension overriding strict ravine limits.'),
('territory.kleinburg.projectTimeline', 'page_service_area_inner', 'text', 'Kleinburg Featured Project Timeline', '11 weeks to hardscaping completion'),
('territory.kleinburg.portfolioTitle', 'page_service_area_inner', 'text', 'Kleinburg Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.kleinburg.portfolioDesc', 'page_service_area_inner', 'text', 'Kleinburg Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Kleinburg.'),
('territory.forest-hill.heroImage', 'page_service_area_inner', 'image', 'Forest Hill Hero Image', '/optimized/webp_gen_luxury_glass_mansion.webp'),
('territory.forest-hill.heroTargetLock', 'page_service_area_inner', 'text', 'Forest Hill Hero Target Lock Focus', 'Target Lock: Forest Hill'),
('territory.forest-hill.heroTitleTop', 'page_service_area_inner', 'text', 'Forest Hill Hero Title Top', 'Surgical Construction in'),
('territory.forest-hill.heroTitleBot', 'page_service_area_inner', 'text', 'Forest Hill Hero Title Bottom', 'Forest Hill'),
('territory.forest-hill.heroDesc', 'page_service_area_inner', 'text', 'Forest Hill Hero Subheadline', 'Zero-error execution in Toronto''s most prestigious old-money enclave.'),
('territory.forest-hill.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Forest Hill Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.forest-hill.bylawsTitle1', 'page_service_area_inner', 'text', 'Forest Hill Bylaws Title Part 1', 'CONQUERING'),
('territory.forest-hill.bylawsTitle2', 'page_service_area_inner', 'text', 'Forest Hill Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.forest-hill.bylawsDesc', 'page_service_area_inner', 'text', 'Forest Hill Bylaws Description', 'You cannot engineer a multi-million dollar estate in Forest Hill without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Forest Hill''s hardest zoning restrictions.'),
('territory.forest-hill.bylaw1Title', 'page_service_area_inner', 'text', 'Forest Hill Bylaw Item 1 Title', 'Deep Underpinning'),
('territory.forest-hill.bylaw1Desc', 'page_service_area_inner', 'text', 'Forest Hill Bylaw Item 1 Description', 'We utilize advanced hydraulic structural shoring to drastically lower original heritage basement footings for 10-foot ceiling clearances.'),
('territory.forest-hill.bylaw2Title', 'page_service_area_inner', 'text', 'Forest Hill Bylaw Item 2 Title', 'Toronto C of A'),
('territory.forest-hill.bylaw2Desc', 'page_service_area_inner', 'text', 'Forest Hill Bylaw Item 2 Description', 'Decades of political capital to bulldoze structural variances through the notoriously difficult midtown Committee of Adjustment.'),
('territory.forest-hill.projectTitle', 'page_service_area_inner', 'text', 'Forest Hill Featured Project Title', 'Forest Hill Foyer Redesign'),
('territory.forest-hill.projectCategory', 'page_service_area_inner', 'text', 'Forest Hill Featured Project Category', 'Luxury Interiors'),
('territory.forest-hill.projectImage', 'page_service_area_inner', 'image', 'Forest Hill Featured Project Image', '/optimized/webp_gen_concrete_contemporary.webp'),
('territory.forest-hill.projectScope', 'page_service_area_inner', 'text', 'Forest Hill Featured Project Scope', 'Total interior skeletal demolition preserving only the exterior century-old brick shell.'),
('territory.forest-hill.projectTimeline', 'page_service_area_inner', 'text', 'Forest Hill Featured Project Timeline', '9 months intensive renovation'),
('territory.forest-hill.portfolioTitle', 'page_service_area_inner', 'text', 'Forest Hill Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.forest-hill.portfolioDesc', 'page_service_area_inner', 'text', 'Forest Hill Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Forest Hill.'),
('territory.bridle-path.heroImage', 'page_service_area_inner', 'image', 'Bridle Path Hero Image', '/optimized/webp_gen_brutalist_villa.webp'),
('territory.bridle-path.heroTargetLock', 'page_service_area_inner', 'text', 'Bridle Path Hero Target Lock Focus', 'Target Lock: Bridle Path'),
('territory.bridle-path.heroTitleTop', 'page_service_area_inner', 'text', 'Bridle Path Hero Title Top', 'Billionaire''s Row: The'),
('territory.bridle-path.heroTitleBot', 'page_service_area_inner', 'text', 'Bridle Path Hero Title Bottom', 'Bridle Path'),
('territory.bridle-path.heroDesc', 'page_service_area_inner', 'text', 'Bridle Path Hero Subheadline', 'Unrivaled scale. Maximum security. Flawless structural supremacy.'),
('territory.bridle-path.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Bridle Path Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.bridle-path.bylawsTitle1', 'page_service_area_inner', 'text', 'Bridle Path Bylaws Title Part 1', 'CONQUERING'),
('territory.bridle-path.bylawsTitle2', 'page_service_area_inner', 'text', 'Bridle Path Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.bridle-path.bylawsDesc', 'page_service_area_inner', 'text', 'Bridle Path Bylaws Description', 'You cannot engineer a multi-million dollar estate in Bridle Path without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Bridle Path''s hardest zoning restrictions.'),
('territory.bridle-path.bylaw1Title', 'page_service_area_inner', 'text', 'Bridle Path Bylaw Item 1 Title', 'Fortification & Setbacks'),
('territory.bridle-path.bylaw1Desc', 'page_service_area_inner', 'text', 'Bridle Path Bylaw Item 1 Description', 'Executing massive custom iron perimeter gates and retaining walls while technically honoring deep city curb setbacks.'),
('territory.bridle-path.bylaw2Title', 'page_service_area_inner', 'text', 'Bridle Path Bylaw Item 2 Title', 'Super-Scale Variances'),
('territory.bridle-path.bylaw2Desc', 'page_service_area_inner', 'text', 'Bridle Path Bylaw Item 2 Description', 'Securing zoning overrides for +20,000 sqft footprints and multi-level subterranean wellness complexes.'),
('territory.bridle-path.projectTitle', 'page_service_area_inner', 'text', 'Bridle Path Featured Project Title', 'The Bridle Path Manor'),
('territory.bridle-path.projectCategory', 'page_service_area_inner', 'text', 'Bridle Path Featured Project Category', 'Custom Home Building'),
('territory.bridle-path.projectImage', 'page_service_area_inner', 'image', 'Bridle Path Featured Project Image', '/optimized/webp_gen_commercial_skyscraper.webp'),
('territory.bridle-path.projectScope', 'page_service_area_inner', 'text', 'Bridle Path Featured Project Scope', 'Completely turn-key 15,000 sqft mega-build featuring acoustic theater isolation.'),
('territory.bridle-path.projectTimeline', 'page_service_area_inner', 'text', 'Bridle Path Featured Project Timeline', '24 months to client handover'),
('territory.bridle-path.portfolioTitle', 'page_service_area_inner', 'text', 'Bridle Path Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.bridle-path.portfolioDesc', 'page_service_area_inner', 'text', 'Bridle Path Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Bridle Path.'),
('territory.rosedale.heroImage', 'page_service_area_inner', 'image', 'Rosedale Hero Image', '/optimized/webp_gen_corporate_lowrise.webp'),
('territory.rosedale.heroTargetLock', 'page_service_area_inner', 'text', 'Rosedale Hero Target Lock Focus', 'Target Lock: Rosedale'),
('territory.rosedale.heroTitleTop', 'page_service_area_inner', 'text', 'Rosedale Hero Title Top', 'Heritage Restoration'),
('territory.rosedale.heroTitleBot', 'page_service_area_inner', 'text', 'Rosedale Hero Title Bottom', 'in Rosedale'),
('territory.rosedale.heroDesc', 'page_service_area_inner', 'text', 'Rosedale Hero Subheadline', 'Preserving a 19th-century facade. Engineering a 21st-century masterwork inside.'),
('territory.rosedale.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Rosedale Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.rosedale.bylawsTitle1', 'page_service_area_inner', 'text', 'Rosedale Bylaws Title Part 1', 'CONQUERING'),
('territory.rosedale.bylawsTitle2', 'page_service_area_inner', 'text', 'Rosedale Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.rosedale.bylawsDesc', 'page_service_area_inner', 'text', 'Rosedale Bylaws Description', 'You cannot engineer a multi-million dollar estate in Rosedale without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Rosedale''s hardest zoning restrictions.'),
('territory.rosedale.bylaw1Title', 'page_service_area_inner', 'text', 'Rosedale Bylaw Item 1 Title', 'Historical Board Protocol'),
('territory.rosedale.bylaw1Desc', 'page_service_area_inner', 'text', 'Rosedale Bylaw Item 1 Description', 'Our architects maintain flawless relations with the Toronto Heritage Preservation Board, executing modern lifts without sparking neighborhood opposition.'),
('territory.rosedale.bylaw2Title', 'page_service_area_inner', 'text', 'Rosedale Bylaw Item 2 Title', 'Zero-Impact Sourcing'),
('territory.rosedale.bylaw2Desc', 'page_service_area_inner', 'text', 'Rosedale Bylaw Item 2 Description', 'We source authentic, century-old reclaimed materials globally to legally pass all facade inspection mandates immediately.'),
('territory.rosedale.projectTitle', 'page_service_area_inner', 'text', 'Rosedale Featured Project Title', 'Rosedale Heritage Revival'),
('territory.rosedale.projectCategory', 'page_service_area_inner', 'text', 'Rosedale Featured Project Category', 'Architectural Renovation'),
('territory.rosedale.projectImage', 'page_service_area_inner', 'image', 'Rosedale Featured Project Image', '/optimized/webp_gen_luxury_kitchen.webp'),
('territory.rosedale.projectScope', 'page_service_area_inner', 'text', 'Rosedale Featured Project Scope', 'Hidden steel I-beam span installations to remove all main floor load-bearing walls.'),
('territory.rosedale.projectTimeline', 'page_service_area_inner', 'text', 'Rosedale Featured Project Timeline', '12 months surgical process'),
('territory.rosedale.portfolioTitle', 'page_service_area_inner', 'text', 'Rosedale Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.rosedale.portfolioDesc', 'page_service_area_inner', 'text', 'Rosedale Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Rosedale.'),
('territory.high-park.heroImage', 'page_service_area_inner', 'image', 'High Park Hero Image', '/optimized/webp_gen_marble_foyer.webp'),
('territory.high-park.heroTargetLock', 'page_service_area_inner', 'text', 'High Park Hero Target Lock Focus', 'Target Lock: High Park'),
('territory.high-park.heroTitleTop', 'page_service_area_inner', 'text', 'High Park Hero Title Top', 'Refined Density in'),
('territory.high-park.heroTitleBot', 'page_service_area_inner', 'text', 'High Park Hero Title Bottom', 'High Park'),
('territory.high-park.heroDesc', 'page_service_area_inner', 'text', 'High Park Hero Subheadline', 'Vertical stacking and lateral additions in heavily restricted zones.'),
('territory.high-park.bylawsSuperTitle', 'page_service_area_inner', 'text', 'High Park Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.high-park.bylawsTitle1', 'page_service_area_inner', 'text', 'High Park Bylaws Title Part 1', 'CONQUERING'),
('territory.high-park.bylawsTitle2', 'page_service_area_inner', 'text', 'High Park Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.high-park.bylawsDesc', 'page_service_area_inner', 'text', 'High Park Bylaws Description', 'You cannot engineer a multi-million dollar estate in High Park without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving High Park''s hardest zoning restrictions.'),
('territory.high-park.bylaw1Title', 'page_service_area_inner', 'text', 'High Park Bylaw Item 1 Title', 'Mature Canopy Law'),
('territory.high-park.bylaw1Desc', 'page_service_area_inner', 'text', 'High Park Bylaw Item 1 Description', 'Navigating the rigid Toronto Forestry mandates surrounding ancient oaks to secure massive rear-yard additions.'),
('territory.high-park.bylaw2Title', 'page_service_area_inner', 'text', 'High Park Bylaw Item 2 Title', 'Geometric Expansion'),
('territory.high-park.bylaw2Desc', 'page_service_area_inner', 'text', 'High Park Bylaw Item 2 Description', 'Solving incredibly narrow lot lines by executing structurally defiant cantilevered second-story extensions.'),
('territory.high-park.projectTitle', 'page_service_area_inner', 'text', 'High Park Featured Project Title', 'The High Park Overlook'),
('territory.high-park.projectCategory', 'page_service_area_inner', 'text', 'High Park Featured Project Category', 'Home Renovations'),
('territory.high-park.projectImage', 'page_service_area_inner', 'image', 'High Park Featured Project Image', '/optimized/webp_gen_boardroom.webp'),
('territory.high-park.projectScope', 'page_service_area_inner', 'text', 'High Park Featured Project Scope', 'Major 3rd-story architectural lift wrapped in imported black limestone.'),
('territory.high-park.projectTimeline', 'page_service_area_inner', 'text', 'High Park Featured Project Timeline', '10 months complete cycle'),
('territory.high-park.portfolioTitle', 'page_service_area_inner', 'text', 'High Park Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.high-park.portfolioDesc', 'page_service_area_inner', 'text', 'High Park Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across High Park.'),
('territory.mississauga.heroImage', 'page_service_area_inner', 'image', 'Mississauga Hero Image', '/optimized/webp_gen_deck_pool.webp'),
('territory.mississauga.heroTargetLock', 'page_service_area_inner', 'text', 'Mississauga Hero Target Lock Focus', 'Target Lock: Mississauga'),
('territory.mississauga.heroTitleTop', 'page_service_area_inner', 'text', 'Mississauga Hero Title Top', 'Modern Progression'),
('territory.mississauga.heroTitleBot', 'page_service_area_inner', 'text', 'Mississauga Hero Title Bottom', 'in Mississauga'),
('territory.mississauga.heroDesc', 'page_service_area_inner', 'text', 'Mississauga Hero Subheadline', 'From Lorne Park to the Credit River. Maximum structural footprint.'),
('territory.mississauga.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Mississauga Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.mississauga.bylawsTitle1', 'page_service_area_inner', 'text', 'Mississauga Bylaws Title Part 1', 'CONQUERING'),
('territory.mississauga.bylawsTitle2', 'page_service_area_inner', 'text', 'Mississauga Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.mississauga.bylawsDesc', 'page_service_area_inner', 'text', 'Mississauga Bylaws Description', 'You cannot engineer a multi-million dollar estate in Mississauga without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Mississauga''s hardest zoning restrictions.'),
('territory.mississauga.bylaw1Title', 'page_service_area_inner', 'text', 'Mississauga Bylaw Item 1 Title', 'Waterfront Proximity'),
('territory.mississauga.bylaw1Desc', 'page_service_area_inner', 'text', 'Mississauga Bylaw Item 1 Description', 'Executing deep, multi-level foundations near the high-water table Credit River using dual-dimple waterproof membranes.'),
('territory.mississauga.bylaw2Title', 'page_service_area_inner', 'text', 'Mississauga Bylaw Item 2 Title', 'Rapid Approvals'),
('territory.mississauga.bylaw2Desc', 'page_service_area_inner', 'text', 'Mississauga Bylaw Item 2 Description', 'Pushing highly aggressive, hyper-modern flat-roof architectural plans through the traditionally conservative Mississauga planning board.'),
('territory.mississauga.projectTitle', 'page_service_area_inner', 'text', 'Mississauga Featured Project Title', 'Lorne Park Modern'),
('territory.mississauga.projectCategory', 'page_service_area_inner', 'text', 'Mississauga Featured Project Category', 'Ground-Up Build'),
('territory.mississauga.projectImage', 'page_service_area_inner', 'image', 'Mississauga Featured Project Image', '/optimized/webp_gen_industrial_loft.webp'),
('territory.mississauga.projectScope', 'page_service_area_inner', 'text', 'Mississauga Featured Project Scope', '5,500 sqft brutalist geometric build over an expansive luxury driveway.'),
('territory.mississauga.projectTimeline', 'page_service_area_inner', 'text', 'Mississauga Featured Project Timeline', '14 months to execute'),
('territory.mississauga.portfolioTitle', 'page_service_area_inner', 'text', 'Mississauga Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.mississauga.portfolioDesc', 'page_service_area_inner', 'text', 'Mississauga Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Mississauga.'),
('territory.toronto.heroImage', 'page_service_area_inner', 'image', 'Toronto Core Hero Image', '/optimized/webp_gen_luxury_glass_mansion.webp'),
('territory.toronto.heroTargetLock', 'page_service_area_inner', 'text', 'Toronto Core Hero Target Lock Focus', 'Target Lock: Toronto Core'),
('territory.toronto.heroTitleTop', 'page_service_area_inner', 'text', 'Toronto Core Hero Title Top', 'Dominating the'),
('territory.toronto.heroTitleBot', 'page_service_area_inner', 'text', 'Toronto Core Hero Title Bottom', 'Toronto Core'),
('territory.toronto.heroDesc', 'page_service_area_inner', 'text', 'Toronto Core Hero Subheadline', 'Surgical execution under the strictest urban bureaucracy in North America.'),
('territory.toronto.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Toronto Core Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.toronto.bylawsTitle1', 'page_service_area_inner', 'text', 'Toronto Core Bylaws Title Part 1', 'CONQUERING'),
('territory.toronto.bylawsTitle2', 'page_service_area_inner', 'text', 'Toronto Core Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.toronto.bylawsDesc', 'page_service_area_inner', 'text', 'Toronto Core Bylaws Description', 'You cannot engineer a multi-million dollar estate in Toronto Core without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Toronto Core''s hardest zoning restrictions.'),
('territory.toronto.bylaw1Title', 'page_service_area_inner', 'text', 'Toronto Core Bylaw Item 1 Title', 'Aggressive Urban Variances'),
('territory.toronto.bylaw1Desc', 'page_service_area_inner', 'text', 'Toronto Core Bylaw Item 1 Description', 'We fight at the Committee of Adjustment to legally stretch your gross floor area logic to the absolute breaking point.'),
('territory.toronto.bylaw2Title', 'page_service_area_inner', 'text', 'Toronto Core Bylaw Item 2 Title', 'Zero-Tolerance WSIB'),
('territory.toronto.bylaw2Desc', 'page_service_area_inner', 'text', 'Toronto Core Bylaw Item 2 Description', 'Operating heavy machinery, cranes, and structural steel deliveries in the core requires military-grade logistical road closures and safety matrices.'),
('territory.toronto.projectTitle', 'page_service_area_inner', 'text', 'Toronto Core Featured Project Title', 'The Annex Annexation'),
('territory.toronto.projectCategory', 'page_service_area_inner', 'text', 'Toronto Core Featured Project Category', 'High-End Renovation'),
('territory.toronto.projectImage', 'page_service_area_inner', 'image', 'Toronto Core Featured Project Image', '/optimized/webp_gen_concrete_contemporary.webp'),
('territory.toronto.projectScope', 'page_service_area_inner', 'text', 'Toronto Core Featured Project Scope', 'Complete structural gutting while wedged inches away from neighboring estates.'),
('territory.toronto.projectTimeline', 'page_service_area_inner', 'text', 'Toronto Core Featured Project Timeline', '13 months of logistics execution'),
('territory.toronto.portfolioTitle', 'page_service_area_inner', 'text', 'Toronto Core Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.toronto.portfolioDesc', 'page_service_area_inner', 'text', 'Toronto Core Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Toronto Core.'),
('territory.markham.heroImage', 'page_service_area_inner', 'image', 'Markham Hero Image', '/optimized/webp_gen_brutalist_villa.webp'),
('territory.markham.heroTargetLock', 'page_service_area_inner', 'text', 'Markham Hero Target Lock Focus', 'Target Lock: Markham'),
('territory.markham.heroTitleTop', 'page_service_area_inner', 'text', 'Markham Hero Title Top', 'Legacy Expansion'),
('territory.markham.heroTitleBot', 'page_service_area_inner', 'text', 'Markham Hero Title Bottom', 'in Markham'),
('territory.markham.heroDesc', 'page_service_area_inner', 'text', 'Markham Hero Subheadline', 'From Unionville to Angus Glen. Building for multi-generational wealth.'),
('territory.markham.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Markham Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.markham.bylawsTitle1', 'page_service_area_inner', 'text', 'Markham Bylaws Title Part 1', 'CONQUERING'),
('territory.markham.bylawsTitle2', 'page_service_area_inner', 'text', 'Markham Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.markham.bylawsDesc', 'page_service_area_inner', 'text', 'Markham Bylaws Description', 'You cannot engineer a multi-million dollar estate in Markham without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Markham''s hardest zoning restrictions.'),
('territory.markham.bylaw1Title', 'page_service_area_inner', 'text', 'Markham Bylaw Item 1 Title', 'Unionville Heritage'),
('territory.markham.bylaw1Desc', 'page_service_area_inner', 'text', 'Markham Bylaw Item 1 Description', 'Strict adherence to the Main Street Heritage conservation limits while radically modernizing interior framing infrastructure.'),
('territory.markham.bylaw2Title', 'page_service_area_inner', 'text', 'Markham Bylaw Item 2 Title', 'Lateral Extensions'),
('territory.markham.bylaw2Desc', 'page_service_area_inner', 'text', 'Markham Bylaw Item 2 Description', 'Aggressive rear and side-yard setback variance applications to achieve maximum structural lot coverage.'),
('territory.markham.projectTitle', 'page_service_area_inner', 'text', 'Markham Featured Project Title', 'Angus Glen Custom'),
('territory.markham.projectCategory', 'page_service_area_inner', 'text', 'Markham Featured Project Category', 'Custom Home Building'),
('territory.markham.projectImage', 'page_service_area_inner', 'image', 'Markham Featured Project Image', '/optimized/webp_gen_commercial_skyscraper.webp'),
('territory.markham.projectScope', 'page_service_area_inner', 'text', 'Markham Featured Project Scope', '7,000 sqft new build engineered for three generations of simultaneous living.'),
('territory.markham.projectTimeline', 'page_service_area_inner', 'text', 'Markham Featured Project Timeline', '15 months full build'),
('territory.markham.portfolioTitle', 'page_service_area_inner', 'text', 'Markham Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.markham.portfolioDesc', 'page_service_area_inner', 'text', 'Markham Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Markham.'),
('territory.etobicoke.heroImage', 'page_service_area_inner', 'image', 'Etobicoke Hero Image', '/optimized/webp_gen_corporate_lowrise.webp'),
('territory.etobicoke.heroTargetLock', 'page_service_area_inner', 'text', 'Etobicoke Hero Target Lock Focus', 'Target Lock: Etobicoke'),
('territory.etobicoke.heroTitleTop', 'page_service_area_inner', 'text', 'Etobicoke Hero Title Top', 'Kingsway To The'),
('territory.etobicoke.heroTitleBot', 'page_service_area_inner', 'text', 'Etobicoke Hero Title Bottom', 'Lakeshore: Etobicoke'),
('territory.etobicoke.heroDesc', 'page_service_area_inner', 'text', 'Etobicoke Hero Subheadline', 'Transforming aging post-war lots into stunning ultra-luxury modernism.'),
('territory.etobicoke.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Etobicoke Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.etobicoke.bylawsTitle1', 'page_service_area_inner', 'text', 'Etobicoke Bylaws Title Part 1', 'CONQUERING'),
('territory.etobicoke.bylawsTitle2', 'page_service_area_inner', 'text', 'Etobicoke Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.etobicoke.bylawsDesc', 'page_service_area_inner', 'text', 'Etobicoke Bylaws Description', 'You cannot engineer a multi-million dollar estate in Etobicoke without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Etobicoke''s hardest zoning restrictions.'),
('territory.etobicoke.bylaw1Title', 'page_service_area_inner', 'text', 'Etobicoke Bylaw Item 1 Title', 'Aggressive Redesign'),
('territory.etobicoke.bylaw1Desc', 'page_service_area_inner', 'text', 'Etobicoke Bylaw Item 1 Description', 'Defeating the stringent Etobicoke side-yard limitations to build wider, massive lateral open-concept floor plans.'),
('territory.etobicoke.bylaw2Title', 'page_service_area_inner', 'text', 'Etobicoke Bylaw Item 2 Title', 'Basement Deepening'),
('territory.etobicoke.bylaw2Desc', 'page_service_area_inner', 'text', 'Etobicoke Bylaw Item 2 Description', 'Excavating aging 6-foot basement ceilings down to 10-foot acoustic insulated entertainment theaters via multi-phase underpinning.'),
('territory.etobicoke.projectTitle', 'page_service_area_inner', 'text', 'Etobicoke Featured Project Title', 'The Kingsway Transformation'),
('territory.etobicoke.projectCategory', 'page_service_area_inner', 'text', 'Etobicoke Featured Project Category', 'Structural Gutting'),
('territory.etobicoke.projectImage', 'page_service_area_inner', 'image', 'Etobicoke Featured Project Image', '/optimized/webp_gen_luxury_kitchen.webp'),
('territory.etobicoke.projectScope', 'page_service_area_inner', 'text', 'Etobicoke Featured Project Scope', 'An intense 4-foot complete structural underpinning for an $800K subterranean suite.'),
('territory.etobicoke.projectTimeline', 'page_service_area_inner', 'text', 'Etobicoke Featured Project Timeline', '5 months to basement completion'),
('territory.etobicoke.portfolioTitle', 'page_service_area_inner', 'text', 'Etobicoke Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.etobicoke.portfolioDesc', 'page_service_area_inner', 'text', 'Etobicoke Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Etobicoke.'),
('territory.north-york.heroImage', 'page_service_area_inner', 'image', 'North York Hero Image', '/optimized/webp_gen_marble_foyer.webp'),
('territory.north-york.heroTargetLock', 'page_service_area_inner', 'text', 'North York Hero Target Lock Focus', 'Target Lock: North York'),
('territory.north-york.heroTitleTop', 'page_service_area_inner', 'text', 'North York Hero Title Top', 'Uncompromised Valuations in'),
('territory.north-york.heroTitleBot', 'page_service_area_inner', 'text', 'North York Hero Title Bottom', 'North York'),
('territory.north-york.heroDesc', 'page_service_area_inner', 'text', 'North York Hero Subheadline', 'Willowdale and Bayview Village''s premier executive builder.'),
('territory.north-york.bylawsSuperTitle', 'page_service_area_inner', 'text', 'North York Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.north-york.bylawsTitle1', 'page_service_area_inner', 'text', 'North York Bylaws Title Part 1', 'CONQUERING'),
('territory.north-york.bylawsTitle2', 'page_service_area_inner', 'text', 'North York Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.north-york.bylawsDesc', 'page_service_area_inner', 'text', 'North York Bylaws Description', 'You cannot engineer a multi-million dollar estate in North York without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving North York''s hardest zoning restrictions.'),
('territory.north-york.bylaw1Title', 'page_service_area_inner', 'text', 'North York Bylaw Item 1 Title', 'Lot Severance Mastery'),
('territory.north-york.bylaw1Desc', 'page_service_area_inner', 'text', 'North York Bylaw Item 1 Description', 'Utilizing aggressive legal restructuring to sever massive legacy lots, instantly generating multi-million dollar equity pipelines.'),
('territory.north-york.bylaw2Title', 'page_service_area_inner', 'text', 'North York Bylaw Item 2 Title', 'Modern Stacking'),
('territory.north-york.bylaw2Desc', 'page_service_area_inner', 'text', 'North York Bylaw Item 2 Description', 'Eradicating traditional low-slung bungalows and engineering massive, steel-braced automated luxury glass vertical stacks.'),
('territory.north-york.projectTitle', 'page_service_area_inner', 'text', 'North York Featured Project Title', 'The Willowdale Twin'),
('territory.north-york.projectCategory', 'page_service_area_inner', 'text', 'North York Featured Project Category', 'Custom Build (Severance)'),
('territory.north-york.projectImage', 'page_service_area_inner', 'image', 'North York Featured Project Image', '/optimized/webp_gen_boardroom.webp'),
('territory.north-york.projectScope', 'page_service_area_inner', 'text', 'North York Featured Project Scope', 'A highly complex lot split resulting in two identical, towering luxury structures.'),
('territory.north-york.projectTimeline', 'page_service_area_inner', 'text', 'North York Featured Project Timeline', '22 months for dual execution'),
('territory.north-york.portfolioTitle', 'page_service_area_inner', 'text', 'North York Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.north-york.portfolioDesc', 'page_service_area_inner', 'text', 'North York Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across North York.'),
('territory.aurora.heroImage', 'page_service_area_inner', 'image', 'Aurora Hero Image', '/optimized/webp_gen_deck_pool.webp'),
('territory.aurora.heroTargetLock', 'page_service_area_inner', 'text', 'Aurora Hero Target Lock Focus', 'Target Lock: Aurora'),
('territory.aurora.heroTitleTop', 'page_service_area_inner', 'text', 'Aurora Hero Title Top', 'Garrison Estates'),
('territory.aurora.heroTitleBot', 'page_service_area_inner', 'text', 'Aurora Hero Title Bottom', 'in Aurora'),
('territory.aurora.heroDesc', 'page_service_area_inner', 'text', 'Aurora Hero Subheadline', 'Mastering the terrain to construct isolated, heavily fortified properties.'),
('territory.aurora.bylawsSuperTitle', 'page_service_area_inner', 'text', 'Aurora Bylaws Super Title', 'RED TAPE ELIMINATION'),
('territory.aurora.bylawsTitle1', 'page_service_area_inner', 'text', 'Aurora Bylaws Title Part 1', 'CONQUERING'),
('territory.aurora.bylawsTitle2', 'page_service_area_inner', 'text', 'Aurora Bylaws Title Part 2', 'LOCAL BYLAWS.'),
('territory.aurora.bylawsDesc', 'page_service_area_inner', 'text', 'Aurora Bylaws Description', 'You cannot engineer a multi-million dollar estate in Aurora without navigating its strict municipal bureaucracy. We guarantee 100% permit clearance by pre-emptively solving Aurora''s hardest zoning restrictions.'),
('territory.aurora.bylaw1Title', 'page_service_area_inner', 'text', 'Aurora Bylaw Item 1 Title', 'Topographical Stabilization'),
('territory.aurora.bylaw1Desc', 'page_service_area_inner', 'text', 'Aurora Bylaw Item 1 Description', 'Engineering massive commercial-grade retaining walls to flatten uneven Aurora moraine lots into perfect pool and hardscape foundations.'),
('territory.aurora.bylaw2Title', 'page_service_area_inner', 'text', 'Aurora Bylaw Item 2 Title', 'Multi-Zone Infrastructure'),
('territory.aurora.bylaw2Desc', 'page_service_area_inner', 'text', 'Aurora Bylaw Item 2 Description', 'Heavy mechanical routing spanning vast linear distances across large suburban lots from the main grid to the estate.'),
('territory.aurora.projectTitle', 'page_service_area_inner', 'text', 'Aurora Featured Project Title', 'The Aurora Perimeter'),
('territory.aurora.projectCategory', 'page_service_area_inner', 'text', 'Aurora Featured Project Category', 'Exterior Improvements'),
('territory.aurora.projectImage', 'page_service_area_inner', 'image', 'Aurora Featured Project Image', '/optimized/webp_gen_industrial_loft.webp'),
('territory.aurora.projectScope', 'page_service_area_inner', 'text', 'Aurora Featured Project Scope', 'Military-grade retaining walls locking a stunning multi-tier infinity pool.'),
('territory.aurora.projectTimeline', 'page_service_area_inner', 'text', 'Aurora Featured Project Timeline', '4 months of heavy earth moving'),
('territory.aurora.portfolioTitle', 'page_service_area_inner', 'text', 'Aurora Portfolio Title', 'LOCAL PORTFOLIO.'),
('territory.aurora.portfolioDesc', 'page_service_area_inner', 'text', 'Aurora Portfolio Desc', 'A curated selection of 4 high-tier architectural executions across Aurora.')
ON CONFLICT (key) DO UPDATE SET section = EXCLUDED.section, type = EXCLUDED.type, label = EXCLUDED.label, value = EXCLUDED.value;
