INSERT INTO site_content (section, key, type, label, value)
VALUES
  ('nav_mega', 'nav.mega.res.title', 'text', 'Residential Title', 'Residential Services Division'),
  ('nav_mega', 'nav.mega.res.desc', 'text', 'Residential Desc', 'This sector focuses on bespoke, single-family, and multi-family living environments.'),
  ('nav_mega', 'nav.mega.res.sec1.title', 'text', 'Res Sec 1 Title', 'Custom Home Building'),
  ('nav_mega', 'nav.mega.res.sec1.item1', 'text', 'Res Sec 1 Item 1', 'New Construction'),
  ('nav_mega', 'nav.mega.res.sec1.item2', 'text', 'Res Sec 1 Item 2', 'Custom Design'),
  ('nav_mega', 'nav.mega.res.sec1.item3', 'text', 'Res Sec 1 Item 3', 'Quality Materials'),
  ('nav_mega', 'nav.mega.res.sec1.item4', 'text', 'Res Sec 1 Item 4', 'Turnkey Solutions'),
  ('nav_mega', 'nav.mega.res.sec2.title', 'text', 'Res Sec 2 Title', 'Home Renovations'),
  ('nav_mega', 'nav.mega.res.sec2.item1', 'text', 'Res Sec 2 Item 1', 'Kitchen Remodeling'),
  ('nav_mega', 'nav.mega.res.sec2.item2', 'text', 'Res Sec 2 Item 2', 'Bathroom Remodeling'),
  ('nav_mega', 'nav.mega.res.sec2.item3', 'text', 'Res Sec 2 Item 3', 'Room Additions'),
  ('nav_mega', 'nav.mega.res.sec2.item4', 'text', 'Res Sec 2 Item 4', 'Whole Home Renovations'),
  ('nav_mega', 'nav.mega.res.sec3.title', 'text', 'Res Sec 3 Title', 'Basement Finishing'),
  ('nav_mega', 'nav.mega.res.sec3.item1', 'text', 'Res Sec 3 Item 1', 'Open Concepts'),
  ('nav_mega', 'nav.mega.res.sec3.item2', 'text', 'Res Sec 3 Item 2', 'Home Theaters'),
  ('nav_mega', 'nav.mega.res.sec3.item3', 'text', 'Res Sec 3 Item 3', 'Guest Suites'),
  ('nav_mega', 'nav.mega.res.sec3.item4', 'text', 'Res Sec 3 Item 4', 'Recreation Rooms'),
  ('nav_mega', 'nav.mega.res.sec4.title', 'text', 'Res Sec 4 Title', 'Exterior Improvements'),
  ('nav_mega', 'nav.mega.res.sec4.item1', 'text', 'Res Sec 4 Item 1', 'Decks & Porches'),
  ('nav_mega', 'nav.mega.res.sec4.item2', 'text', 'Res Sec 4 Item 2', 'Roofing'),
  ('nav_mega', 'nav.mega.res.sec4.item3', 'text', 'Res Sec 4 Item 3', 'Siding'),
  ('nav_mega', 'nav.mega.res.sec4.item4', 'text', 'Res Sec 4 Item 4', 'Windows & Doors'),
  ('nav_mega', 'nav.mega.res.sec4.item5', 'text', 'Res Sec 4 Item 5', 'Fence Installation'),
  ('nav_mega', 'nav.mega.com.title', 'text', 'Commercial Title', 'Commercial Services Division'),
  ('nav_mega', 'nav.mega.com.desc', 'text', 'Commercial Desc', 'This sector must project scalability, compliance, and ROI-driven execution to attract B2B clients.'),
  ('nav_mega', 'nav.mega.com.sec1.title', 'text', 'Com Sec 1 Title', 'Commercial Construction'),
  ('nav_mega', 'nav.mega.com.sec1.item1', 'text', 'Com Sec 1 Item 1', 'Ground-Up Construction'),
  ('nav_mega', 'nav.mega.com.sec1.item2', 'text', 'Com Sec 1 Item 2', 'Design-Build'),
  ('nav_mega', 'nav.mega.com.sec1.item3', 'text', 'Com Sec 1 Item 3', 'Material Sourcing'),
  ('nav_mega', 'nav.mega.com.sec1.item4', 'text', 'Com Sec 1 Item 4', 'Turnkey Solutions'),
  ('nav_mega', 'nav.mega.com.sec2.title', 'text', 'Com Sec 2 Title', 'Commercial Remodeling'),
  ('nav_mega', 'nav.mega.com.sec2.item1', 'text', 'Com Sec 2 Item 1', 'Tenant Build-Outs'),
  ('nav_mega', 'nav.mega.com.sec2.item2', 'text', 'Com Sec 2 Item 2', 'Vanilla Shell Finish'),
  ('nav_mega', 'nav.mega.com.sec2.item3', 'text', 'Com Sec 2 Item 3', 'Office Modernization'),
  ('nav_mega', 'nav.mega.com.sec2.item4', 'text', 'Com Sec 2 Item 4', 'ADA Compliance'),
  ('nav_mega', 'nav.mega.com.sec3.title', 'text', 'Com Sec 3 Title', 'Interior Optimization'),
  ('nav_mega', 'nav.mega.com.sec3.item1', 'text', 'Com Sec 3 Item 1', 'Adaptive Reuse'),
  ('nav_mega', 'nav.mega.com.sec3.item2', 'text', 'Com Sec 3 Item 2', 'Executive Suites'),
  ('nav_mega', 'nav.mega.com.sec3.item3', 'text', 'Com Sec 3 Item 3', 'Cafeteria Builds'),
  ('nav_mega', 'nav.mega.com.sec3.item4', 'text', 'Com Sec 3 Item 4', 'Acoustic Partitioning'),
  ('nav_mega', 'nav.mega.com.sec4.title', 'text', 'Com Sec 4 Title', 'Exterior & Security'),
  ('nav_mega', 'nav.mega.com.sec4.item1', 'text', 'Com Sec 4 Item 1', 'Commercial Roofing'),
  ('nav_mega', 'nav.mega.com.sec4.item2', 'text', 'Com Sec 4 Item 2', 'Facade Upgrades'),
  ('nav_mega', 'nav.mega.com.sec4.item3', 'text', 'Com Sec 4 Item 3', 'Storefront Glazing'),
  ('nav_mega', 'nav.mega.com.sec4.item4', 'text', 'Com Sec 4 Item 4', 'Security Fencing'),
  ('nav_mega', 'nav.mega.how.title', 'text', 'How it Works Title', 'How It Works'),
  ('nav_mega', 'nav.mega.how.step1.title', 'text', 'Step 1 Title', 'Initial Consultation'),
  ('nav_mega', 'nav.mega.how.step1.desc', 'text', 'Step 1 Desc', 'Discuss your vision, site requirements, and timeline with our experts.'),
  ('nav_mega', 'nav.mega.how.step2.title', 'text', 'Step 2 Title', 'Custom Blueprint'),
  ('nav_mega', 'nav.mega.how.step2.desc', 'text', 'Step 2 Desc', 'We engineer a comprehensive plan, from architectural design to permits.'),
  ('nav_mega', 'nav.mega.how.step3.title', 'text', 'Step 3 Title', 'Flawless Execution'),
  ('nav_mega', 'nav.mega.how.step3.desc', 'text', 'Step 3 Desc', 'We build it. You step into a meticulously finished environment.'),
  ('nav_mega', 'nav.mega.how.btn_book', 'text', 'Book Strategy Call Button', 'Book A Free Strategy Call'),
  ('nav_mega', 'nav.mega.how.btn_view', 'text', 'View All Services Button', 'View All Services →'),
  ('nav_mega', 'services.grid.card_subtitle', 'text', 'Services Grid Card Tag', 'Construction Complete'),
  ('nav_mega', 'services.grid.view_button', 'text', 'Services Grid Quick View', 'View Deep Dive'),
  ('page_services', 'new-construction.card.title', 'text', 'New Construction Card Title', 'New Construction'),
  ('page_services', 'new-construction.card.description', 'text', 'New Construction Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to New Construction requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'custom-design.card.title', 'text', 'Custom Design Card Title', 'Custom Design'),
  ('page_services', 'custom-design.card.description', 'text', 'Custom Design Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Custom Design requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'quality-materials.card.title', 'text', 'Quality Materials Card Title', 'Quality Materials'),
  ('page_services', 'quality-materials.card.description', 'text', 'Quality Materials Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Quality Materials requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'turnkey-solutions.card.title', 'text', 'Turnkey Solutions Card Title', 'Turnkey Solutions'),
  ('page_services', 'turnkey-solutions.card.description', 'text', 'Turnkey Solutions Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Turnkey Solutions requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'kitchen-remodeling.card.title', 'text', 'Kitchen Remodeling Card Title', 'Kitchen Remodeling'),
  ('page_services', 'kitchen-remodeling.card.description', 'text', 'Kitchen Remodeling Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Kitchen Remodeling requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'bathroom-remodeling.card.title', 'text', 'Bathroom Remodeling Card Title', 'Bathroom Remodeling'),
  ('page_services', 'bathroom-remodeling.card.description', 'text', 'Bathroom Remodeling Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Bathroom Remodeling requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'room-additions.card.title', 'text', 'Room Additions Card Title', 'Room Additions'),
  ('page_services', 'room-additions.card.description', 'text', 'Room Additions Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Room Additions requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'whole-home-renovations.card.title', 'text', 'Whole Home Renovations Card Title', 'Whole Home Renovations'),
  ('page_services', 'whole-home-renovations.card.description', 'text', 'Whole Home Renovations Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Whole Home Renovations requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'open-concepts.card.title', 'text', 'Open Concepts Card Title', 'Open Concepts'),
  ('page_services', 'open-concepts.card.description', 'text', 'Open Concepts Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Open Concepts requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'home-theaters.card.title', 'text', 'Home Theaters Card Title', 'Home Theaters'),
  ('page_services', 'home-theaters.card.description', 'text', 'Home Theaters Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Home Theaters requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'guest-suites.card.title', 'text', 'Guest Suites Card Title', 'Guest Suites'),
  ('page_services', 'guest-suites.card.description', 'text', 'Guest Suites Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Guest Suites requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'recreation-rooms.card.title', 'text', 'Recreation Rooms Card Title', 'Recreation Rooms'),
  ('page_services', 'recreation-rooms.card.description', 'text', 'Recreation Rooms Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Recreation Rooms requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'decks-porches.card.title', 'text', 'Decks & Porches Card Title', 'Decks & Porches'),
  ('page_services', 'decks-porches.card.description', 'text', 'Decks & Porches Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Decks & Porches requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'roofing.card.title', 'text', 'Roofing Card Title', 'Roofing'),
  ('page_services', 'roofing.card.description', 'text', 'Roofing Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Roofing requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'siding.card.title', 'text', 'Siding Card Title', 'Siding'),
  ('page_services', 'siding.card.description', 'text', 'Siding Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Siding requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'windows-doors.card.title', 'text', 'Windows & Doors Card Title', 'Windows & Doors'),
  ('page_services', 'windows-doors.card.description', 'text', 'Windows & Doors Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Windows & Doors requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'fence-installation.card.title', 'text', 'Fence Installation Card Title', 'Fence Installation'),
  ('page_services', 'fence-installation.card.description', 'text', 'Fence Installation Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Fence Installation requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'ground-up-construction.card.title', 'text', 'Ground-Up Construction Card Title', 'Ground-Up Construction'),
  ('page_services', 'ground-up-construction.card.description', 'text', 'Ground-Up Construction Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Ground-Up Construction requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'design-build.card.title', 'text', 'Design-Build Services Card Title', 'Design-Build Services'),
  ('page_services', 'design-build.card.description', 'text', 'Design-Build Services Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Design-Build Services requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'material-sourcing.card.title', 'text', 'Structural Material Sourcing Card Title', 'Structural Material Sourcing'),
  ('page_services', 'material-sourcing.card.description', 'text', 'Structural Material Sourcing Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Structural Material Sourcing requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'tenant-build-outs.card.title', 'text', 'Tenant Build-Outs Card Title', 'Tenant Build-Outs'),
  ('page_services', 'tenant-build-outs.card.description', 'text', 'Tenant Build-Outs Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Tenant Build-Outs requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'vanilla-shell-finish.card.title', 'text', 'Vanilla Shell Finish Card Title', 'Vanilla Shell Finish'),
  ('page_services', 'vanilla-shell-finish.card.description', 'text', 'Vanilla Shell Finish Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Vanilla Shell Finish requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'office-modernization.card.title', 'text', 'Office Modernization Card Title', 'Office Modernization'),
  ('page_services', 'office-modernization.card.description', 'text', 'Office Modernization Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Office Modernization requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'ada-compliance.card.title', 'text', 'ADA Compliance Retrofitting Card Title', 'ADA Compliance Retrofitting'),
  ('page_services', 'ada-compliance.card.description', 'text', 'ADA Compliance Retrofitting Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to ADA Compliance Retrofitting requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'adaptive-reuse.card.title', 'text', 'Adaptive Reuse Conversions Card Title', 'Adaptive Reuse Conversions'),
  ('page_services', 'adaptive-reuse.card.description', 'text', 'Adaptive Reuse Conversions Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Adaptive Reuse Conversions requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'executive-suites.card.title', 'text', 'Executive Suite Construction Card Title', 'Executive Suite Construction'),
  ('page_services', 'executive-suites.card.description', 'text', 'Executive Suite Construction Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Executive Suite Construction requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'cafeteria-builds.card.title', 'text', 'Breakroom & Cafeteria Builds Card Title', 'Breakroom & Cafeteria Builds'),
  ('page_services', 'cafeteria-builds.card.description', 'text', 'Breakroom & Cafeteria Builds Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Breakroom & Cafeteria Builds requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'acoustic-partitioning.card.title', 'text', 'Acoustic Partitioning Card Title', 'Acoustic Partitioning'),
  ('page_services', 'acoustic-partitioning.card.description', 'text', 'Acoustic Partitioning Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Acoustic Partitioning requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'commercial-roofing.card.title', 'text', 'Commercial Roofing Systems Card Title', 'Commercial Roofing Systems'),
  ('page_services', 'commercial-roofing.card.description', 'text', 'Commercial Roofing Systems Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Commercial Roofing Systems requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'facade-upgrades.card.title', 'text', 'Architectural Facade Upgrades Card Title', 'Architectural Facade Upgrades'),
  ('page_services', 'facade-upgrades.card.description', 'text', 'Architectural Facade Upgrades Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Architectural Facade Upgrades requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'storefront-glazing.card.title', 'text', 'Storefront Glazing & Entry Card Title', 'Storefront Glazing & Entry'),
  ('page_services', 'storefront-glazing.card.description', 'text', 'Storefront Glazing & Entry Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Storefront Glazing & Entry requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.'),
  ('page_services', 'security-fencing.card.title', 'text', 'Perimeter Security Fencing Card Title', 'Perimeter Security Fencing'),
  ('page_services', 'security-fencing.card.description', 'text', 'Perimeter Security Fencing Card Description', 'Emperor Sami transcends standard construction protocols. Our approach to Perimeter Security Fencing requires absolute dedication to structural supremacy. We don''t just execute plans; we forge entirely bespoke architectural solutions.')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
